---

name: Convert LaTeX to PDF
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Compile LaTeX to PDF
        run: pdflatex resume.tex

      - name: Rename from resume.pdf to Alexandre_Jammes_CV.pdf
        run: mv resume.pdf Alexandre_Jammes_CV.pdf

      - name: Move PDF to outputs directory
        run: |
          mkdir -p outputs
          mv Alexandre_Jammes_CV.pdf outputs/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit PDF to the repository
        run: |
          git add outputs/Alexandre_Jammes_CV.pdf
          git commit -m "Add/update PDF output"
          git push origin main
        env:
          GH_TOKEN: ${{ github.token }}
