# .github/workflows/delete-s3-bucket.yml
name: Delete S3 Bucket

on:
  workflow_dispatch:

jobs:
  delete-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1 # Change to your region

    - name: Delete All Objects in S3 Bucket
      run: |
        BUCKET_NAME=${{ secrets.BUCKET_NAME }}
        aws s3 rm s3://$BUCKET_NAME --recursive

    - name: Delete S3 Bucket
      run: |
        BUCKET_NAME=${{ secrets.BUCKET_NAME }}
        aws s3api delete-bucket --bucket $BUCKET_NAME --region ca-central-1
